---
title: "AmCAT website"
theme:
  - cosmo
  - styles.css
---

The Amsterdam Content Analysis Toolkit (AmCAT) is a free open source infrastructure that makes it easy to conduct large-scale automatic and manual content analysis (text analysis) for the social sciences and humanities.
AmCAT aims to make manual and automatic content analysis of various types of texts more easy and accessible.
AmCAT improves the use and the standard of content analysis in the social sciences and humanities, and stimulates the sharing of data and analyses.

The AmCAT system was designed to make it easier to manage (large) content analysis projects.
Documents being one of the essential ingredients, an essential aspect of AmCAT is the storing, viewing, and managing of documents from various sources.
The data are stored in a standard database, to which every user has access for his/her own projects.
The source code for the scripts and website are open source, so everyone is free to setup his/her own server.
The system is designed to make it easy to integrate new analyses, through the website, web services, or through direct access.
AmCAT is designed as an open system, herewith encouraging users to contribute to AmCAT.
The AmCAT designers have tried to make it easy to add functionality, such as upload or scrape scripts or analyses, by using as open standards where applicable and by using a plugin-structure in the places where they expect extensions to be useful.

# Learn more about AmCAT

You can check out the free [**book/manual**](./book/index.html), which shows you how to set up your own AmCAT instance and walks you through conducting your own analyses using AmCAT.


