on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: spin up amcat
        shell: bash
        run: |
          make download-compose-bin compose-file spin-up

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
        
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'
          
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          
      - name: Install system dependecies
        run: |
          sudo apt install -y libcurl4-openssl-dev
      
      - name: Install R Dependencies 
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
      
      - name: Setup reticulate
        shell: Rscript {0}
        run: |
          install.packages('reticulate')
          
          
      - name: Render Quarto Project
        env:
          QUARTO_PRINT_STACK: true
        shell: bash
        run: |
          mkdir -p ./_book/book
          quarto render . --output-dir ./_book/book
          quarto render home.qmd -o index.html
          mv index.html ./_book/index.html
          mv home_files ./_book/home_files
          echo "QUARTO_OUTPUT=./_book/book" >> $GITHUB_ENV
          
      - name: Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          
